const CARD = [
  "🪨 caveman quick reference",
  "",
  "## Modes",
  "| Mode | Trigger | Effect |",
  "|---|---|---|",
  "| Lite | `/caveman lite` | Drop filler. Keep sentences. |",
  "| Full | `/caveman` | Drop articles + filler. Fragments OK. Default. |",
  "| Ultra | `/caveman ultra` | Max terse. Bare fragments. |",
  "| Wenyan-Lite | `/caveman wenyan-lite` | Classical Chinese, light. |",
  "| Wenyan-Full | `/caveman wenyan` | Full 文言文. |",
  "| Wenyan-Ultra | `/caveman wenyan-ultra` | Ancient scholar, max compression. |",
  "",
  "Mode sticks until changed or session ends.",
  "",
  "## Commands",
  "| Command | What |",
  "|---|---|",
  "| `/caveman-commit` | Terse Conventional Commit. ≤50 char subject. |",
  "| `/caveman-review` | One-line PR review: `L42: bug: …` |",
  "| `/caveman-init [--force]` | Drop caveman rule into current repo. |",
  "| `/caveman-stats [--share] [--all] [--since <ISO>]` | Token usage card. |",
  "| `/caveman-help` | This card. |",
  "",
  "## Cavecrew subagents",
  "| Agent | What |",
  "|---|---|",
  "| `cavecrew-investigator` | Read-only code locator. file:line table. |",
  "| `cavecrew-builder` | Surgical 1–2 file edit. Receipt format. |",
  "| `cavecrew-reviewer` | One-line severity-tagged review comments. |",
  "",
  "## Deactivate",
  "Say `stop caveman` or `normal mode`. Resume with `/caveman`.",
  "",
  "## Configure default mode",
  "- Env: `CAVEMAN_DEFAULT_MODE=ultra` (highest priority)",
  '- File: `~/.config/caveman/config.json` → `{"defaultMode":"lite"}`',
  '- Set `"off"` to disable auto-activation.',
  "- Resolution: env > config file > `full`.",
  "",
  "## Docs",
  "https://github.com/josorio7122/pi-caveman",
  "Upstream rules: https://github.com/JuliusBrussee/caveman",
].join("\n");

export function renderHelpCard(): string {
  return CARD;
}
